name: Tourism ML MLOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Register Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python data_register.py

      - name: Prepare Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python data_preparation.py

      - name: Train Model
        run: python model_training.py

      - name: Evaluate Model
        run: python model_evaluation.py

      - name: Push Model to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python push_model_to_hub.py

